name: Bug Report
description: Report a bug in Avotap/css.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Tell us what bug you encountered and what should have happened
    validations:
      required: true
  - type: dropdown
    id: avotap-css-version
    attributes:
      label: The Avotap/css version where this bug is happening.
      options:
        - 'v0.1.2'
        - 'v0.1.1'
        - 'v0.1.0'
        - 'Other (please specify in description)'
    validations:
      required: true
  - type: checkboxes
    id: regression-bug
    attributes:
      label: Is this a regression?
      description: Did this behavior use to work in the previous version?
      options:
        - label: This is a regression bug
          required: false
  - type: dropdown
    id: regression-version
    attributes:
      label: Which version did this behavior use to work in?
      description: In case you checked the regression bug checkbox, please provide the version in which this bug was not present.
      options:
        - 'v0.1.2'
        - 'v0.1.1'
        - 'v0.1.0'
        - 'Other (please specify in description)'
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        Please tell us how to reproduce this bug, for example:
        1. Write '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should be the expected behavior.
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste your screenshots here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Do you want to share any additional context about this bug?
      placeholder: Add any other context about the problem here.
